stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - mvn
    - spr
  script:
    - echo "this is building"
    - hostname
    - mkdir builds
    - touch builds/data.txt
    - echo "true" > builds/data.txt
  artifacts:
    paths:
      - builds/

test:
  stage: test
  tags:
    - mvn
    - spr
  script:
    - echo "this is testing"
    - hostname
    - test -f builds/data.txt
    - grep "true" builds/data.txt

deploy:
  stage: deploy
  tags:
    - mvn
    - spr
  script:
    - sudo apt-get install maven -p etudiant
    - mvn clean package
