stages:
  - build
  - test

build:
  stage: build
  tags:
    - mvn
    - spr
  script:
    - echo "this is building"
    - hostname
    - mkdir builds
    - touch builds/data.txt
    - echo "true" > builds/data.txt
  artifacts:
    paths:
      - builds/

test:
  stage: test
  tags:
    - mvn
    - spr
  script:
    - echo "this is testing"
    - hostname
    - test -f builds/data.txt
    - grep "true" builds/data.txt

deploy:
  stage: deploy
  tags:
    - mvn
    - spr
  script:
    - echo "debut deploy"
    - mvn clean package
    - echo "clean package"
    - mv target/usersspringboot-0.0.1-SNAPSHOT.jar ~/opt/tomcat/apache-tomcat-9.0.31/webapps
    - echo "fin"
