cache:
  key: "$CI_JOB_NAME"
  paths:
    # Must be within the repository under test hence we can't use the
    # default ~/.m2
    - .m2/repository
variables:
  # Use the cached directory above.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

junit:
  image: maven:latest # docker image with Maven
  before_script:
    # The runners on the forge need a proxy to access the web. mvn
    # ignores the $http_proxy & friends variable => write a
    # configuration file that does this for us.
    - . usersspringboot/setup-mvn-proxy.sh
    # Useful only for debugging
    #- cat ~/.m2/settings.xml
  script:
    - cd usersspringboot && mvn test && mvn checkstyle:check
